<?php

namespace Tests;

use App\Models\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{

    /**
     * @var User
     */
    private $user;


    /* вызывается во время инициализации UserTest
     * как __construct()
     * здесь инициализируем необходимые объекты
     */
    protected function setUp(): void
    {
        $this->user = new User('TestName', 'test@email.com', '1234', 23);
    }

    /* вызывается после выполнения тестов
     * как __destruct()
     * здесь обнуляем объекты с которыми работали (очищаем память)
     */
    protected function tearDown(): void
    {

        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function ageProvider()
    {
        return [
            'incorrect' => [22],
            'correct' => [23]
        ];
    }

    /**
     * @dataProvider ageProvider
     */
    public function testAge($age)
    {
        // проверяем равество
        $this->assertEquals($age, $this->user->getAge());
    }

    public function testPass()
    {
        // этот тест провалится
        $this->assertEquals('0000', $this->user->getPass());
    }
}
