version: '3.6'

services:


  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/phpunit
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8086:80"


  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/phpunit
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    environment:
          XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
          PHP_IDE_CONFIG: "serverName=Docker"

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ../:/var/www/phpunit
    command: sleep 10000
    container_name: ${COMPOSE_PROJECT_NAME}-cli

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    ports:
      - "33062:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql: